name: thememode_selector
description: A widget to select between light and dark ThemeMode (in development, but working fine)
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter

