name: design_system
description: A new Flutter package project.
version: 0.0.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  flash: ^1.5.2+2 #Keep this version. Used for display helper (success/error) messages 
  badges: ^2.0.2 #Badges for bottom bar
  statsfl: ^2.3.0 #Perfomance Monitoring
  loader_overlay: ^2.0.7 #Loader Overlay

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.15.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        weight: 100
      - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-Semibold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        weight: 900
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-Semibold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-Black.ttf
        weight: 900
  
