name: services_core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Logs
  logger: ^1.3.0
  #Analytics
  mixpanel_analytics: ^2.1.1
  firebase_analytics: ^10.4.0
  #Configuration
  flutter_dotenv: ^5.0.2
  #Local Storage
  shared_preferences: ^2.1.1
  #Device Info
  universal_platform: ^1.0.0+1
  #Purchases
  purchases_flutter: ^4.12.0
  #Url Launcher
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.3


flutter:
